ruby '2.2.3'
source 'https://rubygems.org'

gem 'seed_dump'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 4.2.4'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
gem 'delayed_job_active_record'
gem 'cancancan'
gem 'vimeo'
gem 'foundation-rails', '~> 5.5.1.2'
gem 'momentjs-rails'

gem 'figaro'

gem 'aws-sdk', '~> 1.66.0'
gem 'fog-aws'
gem 'carrierwave'
gem 'carrierwave_direct'
gem 'delayed_job'

# Use CoffeeScript for .js.coffee assets and views
#gem 'coffee-rails', '~> 4.0.0'

gem 'pg'
gem 'active_model_serializers', github: 'rails-api/active_model_serializers', branch: 'master'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

gem 'google-api-client'

gem 'seedbank'

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem 'bourbon', '~> 4.2.0'
gem 'neat', '~> 1.7.0'

# gem 'angularjs-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

gem 'will_paginate', '~> 3.0'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

gem 'draper'

gem 'capybara-screenshot', :group => :test

group :development do
  gem 'dotenv-rails'
  gem 'guard'
  gem 'guard-livereload', '~> 2.4', require: false
  gem 'letter_opener'
end

group :development, :test do
  gem 'rspec-rails', '~> 2.14'
  gem 'quiet_assets'
  gem 'poltergeist'
  gem 'cucumber-rails', :require => false
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem 'selenium-webdriver', '~> 2.43'
  gem 'simplecov', :require => false
  # Use sqlite3 as the database for Active Record
  gem 'sqlite3'
  gem 'pry'
  gem 'pry-rails'
end

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'rails_12factor', group: [:staging, :production]
gem 'date_validator'
gem 'valid_email2'
gem 'validate_url'
gem 'bcrypt-ruby'
gem 'telestream_cloud'
gem 'ancestry'

gem 'rack-cors', :require => 'rack/cors'
